version: "3.8"
services:
    web:
        build: .
        ports:
            - "6789:8000"
        depends_on:
            - db
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-18.04"
        ports:
          - "1533:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
